version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.12
      nodejs: 10
      python: 3.7
    commands:
      - echo Entered the install phase...
      - apt-get -qq update && apt-get -qq install curl
      - apt-get -qq install asciidoctor
      - curl -s -L https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_0.64.1_Linux-64bit.deb -o hugo.deb
      - dpkg -i hugo.deb
    finally:
      - echo Installation done
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/workshop
      - pip install -r requirements.txt
      - python3 pre_build.py
  build:
    commands:
      - echo Entered the build phase ...
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR/workshop
      - hugo --quiet
    finally:
      - echo Building the HTML files finished
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/workshop
      - python3 post_build.py

artifacts:
  files:
    - "**/*"
    - "*"
  base-directory: $CODEBUILD_SRC_DIR/workshop/public/
  discard-paths: no