# Change these
baseurl = "https://jonahjon.github.io/Workshop-Scaffolding"
title = "Workshop-Scaffolding"

# Don't change these
sectionPagesMenu = "main"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"
min_version = 0.25
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
uglyurls = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"
license = "MIT"

[params]
  editURL = "https://jonahjon.github.io/Workshop-Scaffolding"
  description = "Workshop Scaffolding"
  author = "Jonah Jones"
  themeVariant = "aws"
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableLanguageSwitchingButton = true
  disableShortcutsTitle=true
  disableInlineCopyToClipBoard = true
  pygmentsUseClasses = true
  pygmentsCodeFences = true
  pygmentsCodefencesGuessSyntax = true
  pygmentsStyle = "tango"

[outputs]
page = [ "HTML" ]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> Contact us"
  url = "https://aws.amazon.com"
  weight = 3

[[menu.shortcuts]] 
  name = "<i class='fab fa-github'></i> Github repo"
  identifier = "ds"
  url = "https://github.com/jonahjon/Workshop-Scaffolding"
  weight = 10